/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alan_jniexamples_jnistatic_NativeStatic */

#ifndef _Included_com_alan_jniexamples_jnistatic_NativeStatic
#define _Included_com_alan_jniexamples_jnistatic_NativeStatic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alan_jniexamples_jnistatic_NativeStatic
 * Method:    nativeSetBasicArgs
 * Signature: (IFJZ)I
 */
JNIEXPORT jint JNICALL Java_com_alan_jniexamples_jnistatic_NativeStatic_nativeSetBasicArgs
  (JNIEnv *, jclass, jint, jfloat, jlong, jboolean);

/*
 * Class:     com_alan_jniexamples_jnistatic_NativeStatic
 * Method:    nativeSetStringArgs
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_alan_jniexamples_jnistatic_NativeStatic_nativeSetStringArgs
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
